name: Build, Tag, and Release Application

on:
  push:
    tags:
      - 'v*.*.*-*'

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.4'

      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/.go/pkg/mod
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-

      - name: Build for GitHub Actions
        env:
          PRIVATE_GPG_KEY_GIST_URL: ${{ secrets.PRIVATE_GPG_KEY_GIST_URL }}
          PRIVATE_PGP_KEY_PASSPHRASE: ${{ secrets.PRIVATE_PGP_KEY_PASSPHRASE }}
        run: |
          set -e  # Exit immediately if any command fails
          if [ -z "$PRIVATE_GPG_KEY_GIST_URL" ]; then
            echo "Error: PRIVATE_GPG_KEY_GIST_URL is empty or not set."
            exit 1
          fi
          if [ -z "$PRIVATE_PGP_KEY_PASSPHRASE" ]; then
            echo "Error: PRIVATE_PGP_KEY_PASSPHRASE is empty or not set."
            exit 1
          fi
          curl -s "$PRIVATE_GPG_KEY_GIST_URL" -o crypto/privkey.pem
          if [ ! -s crypto/privkey.pem ]; then
            echo "Error: Failed to download the private GPG key from the Gist."
            exit 1
          fi
          echo "$PRIVATE_PGP_KEY_PASSPHRASE" > crypto/passphrase.txt
          chmod 600 crypto/privkey.pem crypto/passphrase.txt
          make build_gh_actions
          rm -f crypto/privkey.pem crypto/passphrase.txt
          
      - name: Get Version from Makefile
        id: get_version
        run: |
          VERSION=$(make -s version | grep 'Version:' | awk '{print $2}')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Create or Update Git Tag
        id: create_tag
        uses: rickstaa/action-create-tag@v1.7.2
        with:
          tag: ${{ env.VERSION }}
          message: "Release ${{ env.VERSION }}"
          force_push_tag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body: |
            A new release of the application is now available.
            - Version: ${{ env.VERSION }}
          draft: false
          prerelease: ${{ secrets.PRE_RELEASE == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux AMD64 Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ksau-go-linux-amd64
          asset_name: ksau-go-linux-amd64
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows AMD64 Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ksau-go-windows-amd64.exe
          asset_name: ksau-go-windows-amd64.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux ARM64 Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ksau-go-linux-arm64
          asset_name: ksau-go-linux-arm64
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Android ARM64 Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ksau-go-android-arm64
          asset_name: ksau-go-android-arm64
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
